task :default => :test
task :test do
	Dir.glob('./test/**/*_test.rb').each{|file|require file}
end

task :create do
  system("ruby script/create_table.rb")
end

task :drop do
  system("ruby script/drop_table.rb")
end

task :rank do
  system("ruby template/ranking.rb")
end

task :clean do
  system("ruby script/drop_table.rb")
  system("ruby script/create_table.rb")
end

task :battle do
  1.times do
    system("ruby bin/samurai")
  end
end
